# Diese Konfiguration ist als Erweiterung von docker-compose.yml zu benutzen.
# > docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3.0"
services:
  web:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
        - WITH_COMPOSER=true
        - WITH_LUMENINSTALLER=true
        - WITH_SWAGGERPHP=true
        - WITH_PHPUNIT=true
    image: lumen-8
#    command: --with-artisan-migrate
    volumes:
      - ./service:/var/www/html/
