version: "3.0"
services:
  web:
    build:
      context: ..
      args:
        - WITH_XDEBUG=true
        - WITH_COMPOSER=true
        - WITH_LUMENINSTALLER=true
        - WITH_SWAGGERPHP=true
        - WITH_PHPUNIT=true
    image: ${IMAGENAME}
    container_name: ${WEBCONTAINER}
    command: --with-artisan-migrate
    volumes:
      - ../service:/var/www/html/